### ISSUE TITLE
tableData.tHeadings.element$?.[heading] is not a function

### ISSUE THREAD

**Issue by LazyClicks** [jimmynguyen1308/qwik-table-loader#3]
trying to use the example you put but it doesnt seem to work

full error

```
 at eval (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:136:134)
    at Proxy.map (<anonymous>)
    at AsyncFunction.TableLoader_component_NfrI9eWt0og (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:120:104)
    at AsyncFunction.invokeApply (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:3583:22)
    at AsyncFunction.invoke (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:3576:22)
    at eval (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:7123:25)
    at maybeThen (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:379:54)
    at eval (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:7109:14)
    at eval (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28), <anonymous>:3732:25)
    at safeCall (eval at instantiateModule (file:///C:/Users/ayoub/Desktop/playing%20around/table-test/node_modules/.pnpm/vite@5.0.6_@types+node@20.10.4/node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:50162:28
```

running using qwik 1.1.3

**Comment by jimmynguyen1308** [comment]
Hey @LazyClicks,

Sorry for the laaaaaaaaaaaate reply.

I built this library using macOS and Yarn package manager.
I have installed the modules using yarn, pnpm and bun and it seemed to be fine.
With your error log above, it might be something to do with the different OS alongside with incompatible package manager.
My guess is that you should test installing the modules with either npm (which seems to be the most stable on Windows) or Yarn.

Regards.

Update: v0.1.0 is out with:
- Better structure that fits Qwik new direction (so its less likely to have bugs)
- Detailed examples
